db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: splash
    MYSQL_PASSWORD: splash
    MYSQL_DATABASE: SplashCodeTest

web:
  build: .
  volumes:
    - "./www:/www"
  links:
    - db
  ports:
    - "8080:80"
