db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: splash
    MYSQL_PASSWORD: splash
    MYSQL_DATABASE: SplashCodeTest
  volumes:
    - "./:docker-entrypoint-initdb.d"

web:
  build: .
  volumes:
    - "./html:/usr/share/nginx/html"
  links:
    - db
    - fpm
  ports:
    - "8080:80"

fpm:
    image: php:fpm
    ports:
        - ":9000"
    volumes:
        - ./html:/usr/share/nginx/html
